const frame=document.getElementById("live-frame");
const player=document.getElementById("live-player");
const closePlayer=document.getElementById("live-close");
const playerTitle=document.getElementById("live-player-title");
const playerMeta=document.getElementById("live-player-meta");
const playerLoading=document.getElementById("live-player-loading");
const search=document.getElementById("live-search");
const grid=document.getElementById("live-channel-grid");
const guideStatus=document.getElementById("live-guide-status");
const filtersRoot=document.querySelector(".vivid-live-filters");
const FALLBACK=[{id:"atv-international",name:"&TV International",category:"international",country:"India",language:"hin",streamUrl:"https://www.2embed.online/iptv/stream.php?url=N2lFS2R2cHpjbmFSSFRCNG5TOTI3MDFaS2xKWW1saFVwOUdVRDRqMEhlRXdMcmc4NHpLTERrWTZOY2NIdGdmblVXOWJKMFRYTmZzdE1HcWNoemdMZUk3NUZPUUdHMi92L1RUMkZYZ291NHlGZTRTOTJOUTVnZnA1Vm1QSzdvUGs4b0NtNS9qaTlJcVFMWERyZW92REF5QnFMM24yWkhnZEh2bHRyUTY3ZGg4PTo6DPl8NG74VB9DVg1WkNPVKg%3D%3D&title=%26TV+International&qualities=Auto,1080p,720p,480p,360p"}];
let channels=[],activeFilter="all";
const esc=v=>String(v).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
function renderFilters(){if(!filtersRoot)return;const cats=[...new Set(channels.map(c=>c.category).filter(Boolean))].sort(),countries=[...new Set(channels.map(c=>c.country).filter(Boolean))].sort();const opts=[["all","All"],...cats.map(v=>["category:"+v,v]),...countries.map(v=>["country:"+v,v])];filtersRoot.innerHTML=opts.map((o,i)=>`<button class="${i?"":"is-active"}" type="button" data-live-filter="${esc(o[0])}">${esc(o[1])}</button>`).join("");filtersRoot.querySelectorAll("[data-live-filter]").forEach(b=>b.onclick=()=>{activeFilter=b.dataset.liveFilter;filtersRoot.querySelectorAll("[data-live-filter]").forEach(x=>x.classList.toggle("is-active",x===b));render()})}
function visible(){const q=(search?.value||"").trim().toLowerCase();return channels.filter(c=>(activeFilter==="all"||activeFilter==="category:"+c.category||activeFilter==="country:"+c.country)&&(!q||[c.name,c.country,c.category,c.language].filter(Boolean).join(" ").toLowerCase().includes(q)))}
function render(){const list=visible();grid.innerHTML=list.length?list.map(c=>`<button class="vivid-live-channel" type="button" data-channel-id="${esc(c.id)}"><span class="vivid-live-channel-art" aria-hidden="true"><i class="bi bi-broadcast"></i></span><span class="vivid-live-channel-copy"><strong>${esc(c.name)}</strong><small>${esc([c.country,c.language].filter(Boolean).join(" · ")||"Live")}</small></span><span class="vivid-live-channel-play" aria-hidden="true"><i class="bi bi-play-fill"></i></span></button>`).join(""):`<div class="vivid-live-empty"><i class="bi bi-tv"></i><strong>No channels found</strong><span>Try another search or filter.</span></div>`;if(guideStatus)guideStatus.textContent=`${list.length.toLocaleString()} of ${channels.length.toLocaleString()} channels in this guide.`}
function play(c){if(!c?.streamUrl)return;if(playerTitle)playerTitle.textContent=c.name;if(playerMeta)playerMeta.textContent=`${c.country||"International"} · 2Embed live stream`;if(playerLoading)playerLoading.hidden=false;player.hidden=false;frame.src=c.streamUrl;player.scrollIntoView({behavior:"smooth",block:"start"})}
function close(){frame.src="about:blank";player.hidden=true;if(playerLoading)playerLoading.hidden=true}
grid?.addEventListener("click",e=>{const b=e.target.closest("[data-channel-id]");if(b)play(channels.find(c=>c.id===b.dataset.channelId))});
closePlayer?.addEventListener("click",close);frame?.addEventListener("load",()=>{if(playerLoading)playerLoading.hidden=true});search?.addEventListener("input",render);
(async()=>{try{const r=await fetch("./data/live-channels.json",{cache:"no-store"});if(!r.ok)throw Error(r.status);channels=await r.json();if(!Array.isArray(channels)||!channels.length)throw Error("empty")}catch(e){console.warn("Vivid Live catalogue unavailable; using verified seed.",e);channels=FALLBACK}renderFilters();render()})();