import {tmdbApi} from "./tmdb.js";
import {getImageUrl,getMediaUrl} from "./media.js";
import {escapeHtml} from "./utils.js";
import {addCinemaReminder,addCinemaReminderToCalendar,hasCinemaReminder,requestCinemaNotifications,startCinemaReminderLoop} from "./cinema-reminders.js";
const $=id=>document.getElementById(id);
const state={stories:[]};
const dateOnly=x=>String(x||"").slice(0,10);
const pretty=x=>{if(!x)return "Release date TBA";const d=new Date(x+"T00:00:00");return Number.isNaN(d.getTime())?"Release date TBA":d.toLocaleDateString(undefined,{month:"short",day:"numeric",year:"numeric"})};
function storyCard(s){
 const reminder=hasCinemaReminder(s.id,s.kind);
 return '<article class="vivid-news-card"><a class="vivid-news-image" href="'+getMediaUrl({id:s.id,media_type:s.media_type})+'"><img src="'+getImageUrl(s.backdrop_path||s.poster_path,"w780")+'" alt="'+escapeHtml(s.title)+'" loading="lazy"><span>'+escapeHtml(s.label)+'</span></a><div class="vivid-news-body"><small>'+escapeHtml(s.meta)+'</small><h2>'+escapeHtml(s.headline)+'</h2><p>'+escapeHtml(s.copy)+'</p><div class="vivid-news-actions"><a href="'+getMediaUrl({id:s.id,media_type:s.media_type})+'">Explore</a>'+(s.when?'<button class="vivid-notify-release" data-id="'+s.id+'" data-type="'+s.media_type+'" data-kind="'+s.kind+'" '+(reminder?"disabled":"")+'>'+(reminder?"Reminded":"Notify me")+'</button>':"")+'</div></div></article>';
}
function render(filter="all"){const el=$("news-grid");const list=filter==="all"?state.stories:state.stories.filter(x=>x.category===filter);el.innerHTML=list.length?list.map(storyCard).join(""):'<div class="vivid-news-empty">Nothing new in this category yet.</div>';wire();}
function wire(){document.querySelectorAll(".vivid-news-filter").forEach(b=>b.onclick=()=>{document.querySelectorAll(".vivid-news-filter").forEach(x=>x.classList.remove("is-active"));b.classList.add("is-active");render(b.dataset.filter)});document.querySelectorAll(".vivid-notify-release").forEach(b=>b.onclick=async()=>{const s=state.stories.find(x=>String(x.id)===b.dataset.id&&x.media_type===b.dataset.type&&x.kind===b.dataset.kind);if(!s)return;try{const r=addCinemaReminder({title:s.title,when:s.when,note:s.headline,contentId:s.id,mediaType:s.media_type,kind:s.kind});try{await requestCinemaNotifications()}catch{}b.disabled=true;b.textContent="Reminded";$("news-toast").textContent="Release reminder saved · "+pretty(s.when);$("news-toast").hidden=false;setTimeout(()=>{$("news-toast").hidden=true},3500);const cal=$("calendar-"+s.id);if(cal)cal.hidden=false;state.stories=state.stories.map(x=>x===s?{...x,reminder:r}:x)}catch(e){$("news-toast").textContent=e.message||"Could not save reminder.";$("news-toast").hidden=false}});document.querySelectorAll(".vivid-calendar-add").forEach(b=>b.onclick=()=>{const r=JSON.parse(b.dataset.reminder);addCinemaReminderToCalendar(r);b.hidden=true});}
async function load(){const [upcoming,airing,trending]=await Promise.allSettled([tmdbApi.upcomingMovies(1),tmdbApi.airingTodayTv(1),tmdbApi.trending("all","week")]);const stories=[];const push=(x,category,label,headline,copy,kind,when)=>{if(!x?.id)return;stories.push({id:String(x.id),media_type:x.media_type||"movie",title:x.title||x.name||"Untitled",poster_path:x.poster_path,backdrop_path:x.backdrop_path,category,label,headline,copy,kind,when,meta:when?pretty(when):"This week"})};(upcoming.value?.results||[]).slice(0,6).forEach(x=>push({...x,media_type:"movie"},"releases","RELEASE RADAR",(x.title||"A new movie")+" is coming.","Track the release and get a Vivid reminder when it lands.","release",x.release_date));(airing.value?.results||[]).slice(0,6).forEach(x=>push({...x,media_type:"tv"},"episodes","NEW EPISODES",(x.name||"A series")+" has a new episode.","Catch up with what is airing today.","episode",new Date().toISOString().slice(0,10)));(trending.value?.results||[]).filter(x=>x.media_type==="tv").slice(0,4).forEach(x=>push(x,"seasons","SERIES WATCH",(x.name||"A series")+" is heating up.","A trending series worth keeping on your radar.","series",null));state.stories=stories;render();$("news-loading").hidden=true}
$("news-refresh").onclick=()=>{ $("news-loading").hidden=false;void load()};startCinemaReminderLoop();load().catch(()=>{$("news-loading").textContent="Cinema news is temporarily unavailable."});